### ISSUE TITLE
無法批量改名

### ISSUE THREAD

**Issue by koyia** [asadman1523/odvrt#2]
單個沒有問題，但似乎只要是批量就不行了，每次只能改1到2個，然後就會提示失敗。如圖，
![image](https://user-images.githubusercontent.com/76946408/103528452-f2d91d80-4ebe-11eb-9e60-11eb54b7ff97.png)

重複了好多次，就這樣。單個就沒問題，每個都能抓到番號並改名。是不是因為抓番號的伺服器限制了，能不能把批量的改名設置間隔？變成簡單的每幾秒抓一次？

**Comment by koyia** [comment]
![Uploading image.png…]()

**Comment by koyia** [comment]
![image](https://user-images.githubusercontent.com/76946408/103529485-bb6b7080-4ec0-11eb-94f7-31243a1568f8.png)

**Comment by asadman1523** [comment]
請服用1.3.1版
https://github.com/asadman1523/odvrt/releases/tag/1.3.1
