### ISSUE TITLE
命名時發生錯誤訊息 "檔案名稱、目錄名稱或磁碟區標籤語法錯誤。" 

### ISSUE THREAD

**Issue by panoxyl** [asadman1523/odvrt#3]
以SVDVD-769為例,命名時發生錯誤訊息 "檔案名稱、目錄名稱或磁碟區標籤語法錯誤。"  ,
測試了幾次,發現更名時只要有title就會這樣,單單女優名稱、番號是正常的,提供給您做參考。
![image](https://user-images.githubusercontent.com/84296779/118419399-71a45980-b6ee-11eb-8f2e-96f9c44e8986.png)

**Comment by asadman1523** [comment]
檔名有特殊字元，新版已經修正了

https://github.com/asadman1523/Odvrt/releases/tag/1.3.4
